# This file should contain all the record creation needed to seed the database with its default VALUES.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Idea.destroy_all
Endorsement.destroy_all


ideas= Idea.create!([{author:"Earl Ferguson",title:"non sodales sed tincidunt",content:"ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea"},
{author:"Helen Lynch",title:"blandit non",content:"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis"},
{author:"Mary Nelson",title:"turpis nec euismod scelerisque",content:"nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam"},
{author:"Roy Fernandez",title:"habitasse platea dictumst morbi vestibulum velit",content:"duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim"},
{author:"Margaret Graham",title:"nullam molestie nibh in lectus pellentesque",content:"nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed"},
{author:"Ralph Reyes",title:"lorem quisque ut",content:"augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla"},
{author:"Henry Mendoza",title:"massa quis augue",content:"curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere"},
{author:"Alan Hughes",title:"hac habitasse platea",content:"justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor"},
{author:"Doris Mccoy",title:"magnis dis",content:"fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in"},
{author:"Brenda Wagner",title:"volutpat erat",content:"pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at"},
{author:"Frances Stone",title:"venenatis tristique fusce congue diam",content:"gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula"},
{author:"Nicole Lynch",title:"mus etiam vel augue vestibulum",content:"arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget"},
{author:"Michael Young",title:"tempor convallis",content:"tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna"},
{author:"Shirley Myers",title:"orci luctus et ultrices",content:"non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus"},
{author:"Rebecca Barnes",title:"curae mauris viverra diam",content:"tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce"},
{author:"Melissa Hunt",title:"et eros vestibulum ac est lacinia",content:"primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo"},
{author:"Johnny Johnston",title:"amet sapien dignissim vestibulum",content:"vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus"},
{author:"Eugene Cunningham",title:"volutpat dui maecenas",content:"velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio"},
{author:"Jose Cunningham",title:"duis bibendum morbi non",content:"sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus"},
{author:"Russell Ross",title:"justo morbi",content:"nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo"},
{author:"Anna Gutierrez",title:"sit amet diam in magna",content:"amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien"},
{author:"Shawn Robertson",title:"tincidunt eu felis fusce posuere",content:"quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin"},
{author:"Wayne Hansen",title:"donec pharetra magna vestibulum aliquet",content:"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia"},
{author:"Andrea Morris",title:"cum sociis natoque",content:"ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum"},
{author:"Janet Richardson",title:"fusce lacus purus aliquet",content:"et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae"},
{author:"Patricia Olson",title:"nullam orci pede venenatis non sodales",content:"amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis"},
{author:"Clarence Scott",title:"lacinia aenean",content:"rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est"},
{author:"Diane Kelly",title:"non mattis pulvinar nulla pede ullamcorper",content:"eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate"},
{author:"Bobby Lane",title:"eleifend donec",content:"a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper"},
{author:"Jessica Castillo",title:"est phasellus sit amet",content:"mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam"},
{author:"Martin Walker",title:"suscipit a feugiat et",content:"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor"},
{author:"Sandra Lynch",title:"amet consectetuer adipiscing",content:"vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras"},
{author:"Judith Montgomery",title:"tempus sit amet",content:"lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla"},
{author:"Joe Mills",title:"magna ac consequat metus sapien ut",content:"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit"},
{author:"Robert Mendoza",title:"vel pede morbi",content:"mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae"},
{author:"Lawrence Vasquez",title:"vulputate luctus cum",content:"sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut"},
{author:"Dennis Olson",title:"mi sit amet lobortis",content:"tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus"},
{author:"Edward Gilbert",title:"curae duis faucibus accumsan odio curabitur",content:"nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus"},
{author:"Robin Woods",title:"sem mauris",content:"amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer"},
{author:"Melissa Flores",title:"felis sed interdum venenatis turpis",content:"sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus"},
{author:"Billy Mitchell",title:"faucibus cursus urna ut tellus nulla",content:"justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum"},
{author:"Lawrence Fox",title:"convallis tortor risus dapibus augue",content:"vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est"},
{author:"James Morris",title:"varius nulla",content:"vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod"},
{author:"Julie Carr",title:"leo maecenas pulvinar",content:"justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et"},
{author:"Jean Carr",title:"vel nulla eget",content:"laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh"},
{author:"Sandra Peterson",title:"lectus in est",content:"sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus"},
{author:"Patrick Freeman",title:"ante vivamus tortor duis mattis",content:"id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet"},
{author:"Albert Powell",title:"fusce lacus",content:"cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis"},
{author:"Robin Hicks",title:"justo maecenas rhoncus",content:"sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi"},
{author:"Julia Gilbert",title:"vestibulum eget",content:"elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in"},
{author:"Virginia Ellis",title:"eu orci mauris",content:"eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue"},
{author:"Joshua Smith",title:"tellus nisi eu",content:"metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et"},
{author:"Linda Coleman",title:"purus eu magna vulputate luctus",content:"morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante"},
{author:"Mark Hansen",title:"phasellus id sapien in",content:"quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit"},
{author:"Jennifer Morrison",title:"sit amet nulla",content:"ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel"},
{author:"Brandon Cole",title:"faucibus cursus urna",content:"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare"},
{author:"Benjamin West",title:"cursus vestibulum proin",content:"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula"},
{author:"Paul Wheeler",title:"quis lectus suspendisse",content:"pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu"},
{author:"Harry Hunter",title:"elit proin risus praesent",content:"congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla"},
{author:"Antonio Fowler",title:"erat nulla tempus vivamus in felis",content:"nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac"},
{author:"Lori Nichols",title:"libero nam dui proin leo",content:"in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu"},
{author:"Jane Mendoza",title:"vestibulum aliquet ultrices",content:"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam"},
{author:"Albert Henry",title:"in magna bibendum imperdiet",content:"libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu"},
{author:"Billy Burton",title:"nulla mollis molestie lorem",content:"potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque"},
{author:"Joan Schmidt",title:"non mattis pulvinar nulla pede ullamcorper",content:"dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat"},
{author:"Tammy Grant",title:"nec nisi volutpat eleifend donec ut",content:"scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui"},
{author:"Heather Cox",title:"nulla dapibus dolor vel",content:"pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod"},
{author:"Henry Berry",title:"sed interdum venenatis turpis enim blandit",content:"amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non"},
{author:"Ernest Bradley",title:"sapien cursus vestibulum proin eu",content:"nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis"},
{author:"Phyllis Stevens",title:"dapibus nulla suscipit ligula in",content:"libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus"},
{author:"Wanda Banks",title:"condimentum neque sapien placerat ante nulla",content:"rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est"},
{author:"Robin Jordan",title:"nulla nunc purus phasellus in",content:"felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit"},
{author:"Kimberly Tucker",title:"eget eleifend luctus",content:"viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta"},
{author:"Benjamin Rose",title:"eu orci mauris lacinia sapien",content:"vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae"},
{author:"Earl Mccoy",title:"sociis natoque",content:"sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus"},
{author:"Gerald Richardson",title:"nisl venenatis lacinia aenean sit amet",content:"porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla"},
{author:"Benjamin Henry",title:"tincidunt ante vel ipsum praesent blandit",content:"lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id"},
{author:"Martin Montgomery",title:"arcu libero rutrum",content:"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst"},
{author:"Arthur Cunningham",title:"sem sed sagittis nam",content:"adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu"},
{author:"Kathleen Fowler",title:"adipiscing lorem vitae",content:"in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id"},
{author:"Emily Martin",title:"congue eget semper rutrum",content:"ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac"},
{author:"Janet Harris",title:"erat tortor",content:"orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus"},
{author:"Carl Perez",title:"accumsan odio curabitur convallis duis consequat",content:"cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce"},
{author:"Justin Wells",title:"vitae mattis nibh ligula",content:"lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque"},
{author:"Janice Reynolds",title:"tristique tortor eu",content:"quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit"},
{author:"Melissa Hicks",title:"in sapien iaculis congue",content:"odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque"},
{author:"Sean Fowler",title:"etiam faucibus",content:"phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis"},
{author:"Barbara Rose",title:"nulla suscipit ligula in lacus",content:"ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi"},
{author:"Barbara Foster",title:"blandit non interdum in ante",content:"sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut"},
{author:"Heather Cook",title:"imperdiet et commodo vulputate justo in",content:"metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum"},
{author:"Wayne Cunningham",title:"luctus rutrum",content:"donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper"},
{author:"Phyllis Wells",title:"non mattis pulvinar nulla pede",content:"pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero"},
{author:"Jose Holmes",title:"aliquam quis turpis eget elit",content:"vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus"},
{author:"Antonio Ford",title:"non pretium quis lectus suspendisse",content:"curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam"},
{author:"Dennis Stevens",title:"orci vehicula condimentum curabitur",content:"dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu"},
{author:"Carlos Romero",title:"nibh in quis",content:"dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam"},
{author:"Kimberly Wells",title:"nunc vestibulum ante ipsum primis in",content:"volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum"},
{author:"Arthur Chapman",title:"iaculis diam erat fermentum",content:"proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis"},
{author:"Adam Reynolds",title:"vel lectus",content:"eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo"},
{author:"Harry Grant",title:"duis bibendum morbi non",content:"quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum"}
])


endorsements = Endorsement.create!([{author:"Ruby Harris",amount:496.87,idea_id:52},
{author:"Fred Jackson",amount:7267.11,idea_id:19},
{author:"Phillip Evans",amount:6321.01,idea_id:33},
{author:"Frank Knight",amount:9677.69,idea_id:13},
{author:"Larry Wright",amount:1941.4,idea_id:48},
{author:"William Perry",amount:901.44,idea_id:56},
{author:"Rachel Rice",amount:8965.21,idea_id:74},
{author:"Ronald Hill",amount:8166.88,idea_id:55},
{author:"Mary Long",amount:2976.76,idea_id:19},
{author:"Janet Ruiz",amount:7822.52,idea_id:69},
{author:"Gloria Evans",amount:1550.95,idea_id:19},
{author:"Norma Williamson",amount:877.44,idea_id:5},
{author:"Katherine Davis",amount:1813.79,idea_id:45},
{author:"Wanda Bailey",amount:5201.73,idea_id:99},
{author:"Kathy Alexander",amount:4343.69,idea_id:68},
{author:"Martin Watson",amount:174.15,idea_id:27},
{author:"Fred Carr",amount:6667.98,idea_id:56},
{author:"Jack Butler",amount:7646.29,idea_id:18},
{author:"Ronald Lawrence",amount:5401.99,idea_id:97},
{author:"Ryan Cook",amount:9427.99,idea_id:52},
{author:"Phillip Hall",amount:7669.89,idea_id:32},
{author:"Brenda Andrews",amount:3988.26,idea_id:49},
{author:"Eugene Tucker",amount:7533.07,idea_id:87},
{author:"Judy Duncan",amount:1028.45,idea_id:10},
{author:"Martin Fields",amount:1616.62,idea_id:75},
{author:"Teresa Collins",amount:9603.83,idea_id:56},
{author:"Patricia Dunn",amount:1695.44,idea_id:65},
{author:"Kenneth Mason",amount:4988.19,idea_id:4},
{author:"Patrick Hughes",amount:6809.8,idea_id:46},
{author:"Ruth Rice",amount:4891.49,idea_id:75},
{author:"Philip Kelly",amount:4770.03,idea_id:66},
{author:"Stephen Russell",amount:9637.02,idea_id:13},
{author:"Ruby Hall",amount:276.81,idea_id:81},
{author:"Stephen Gonzalez",amount:2082.9,idea_id:87},
{author:"Catherine Diaz",amount:8743.64,idea_id:30},
{author:"Keith Martinez",amount:1858.86,idea_id:70},
{author:"Brenda Henry",amount:7328.86,idea_id:30},
{author:"Willie Gibson",amount:2788.0,idea_id:4},
{author:"Bobby Bennett",amount:6918.31,idea_id:70},
{author:"Melissa Murray",amount:9463.98,idea_id:79},
{author:"Rachel Bishop",amount:3661.39,idea_id:79},
{author:"Denise Murphy",amount:8970.59,idea_id:25},
{author:"Janet Walker",amount:5313.59,idea_id:81},
{author:"Stephen Fields",amount:6563.02,idea_id:20},
{author:"Brenda Palmer",amount:954.84,idea_id:12},
{author:"Nancy Thomas",amount:8789.34,idea_id:49},
{author:"Andrew Adams",amount:3655.02,idea_id:31},
{author:"Henry Oliver",amount:6279.51,idea_id:25},
{author:"Gerald Dunn",amount:4458.26,idea_id:70},
{author:"Irene Hunter",amount:3451.16,idea_id:35},
{author:"Benjamin Green",amount:6418.02,idea_id:73},
{author:"Scott Bowman",amount:3076.12,idea_id:93},
{author:"Johnny Kim",amount:5578.63,idea_id:63},
{author:"Marie Greene",amount:7283.02,idea_id:15},
{author:"Jane Freeman",amount:6018.88,idea_id:95},
{author:"Craig Wheeler",amount:9588.58,idea_id:98},
{author:"Earl Webb",amount:9812.22,idea_id:37},
{author:"Jonathan Chapman",amount:1408.78,idea_id:54},
{author:"Wayne Lawson",amount:8204.41,idea_id:43},
{author:"Sharon Daniels",amount:5894.03,idea_id:21},
{author:"Angela Hanson",amount:9806.29,idea_id:94},
{author:"Todd Mills",amount:1364.57,idea_id:94},
{author:"Doris Simmons",amount:3947.94,idea_id:50},
{author:"Mark Brown",amount:120.22,idea_id:47},
{author:"Edward Garcia",amount:7139.14,idea_id:93},
{author:"Christine Nelson",amount:5353.37,idea_id:39},
{author:"Anthony Bryant",amount:969.4,idea_id:54},
{author:"Howard Cook",amount:6082.46,idea_id:97},
{author:"Elizabeth Ellis",amount:3501.99,idea_id:65},
{author:"Mark Bailey",amount:4546.99,idea_id:80},
{author:"Steve Palmer",amount:7402.78,idea_id:6},
{author:"Edward Ramirez",amount:4007.2,idea_id:72},
{author:"Harry Palmer",amount:6005.91,idea_id:9},
{author:"Maria Stanley",amount:544.08,idea_id:38},
{author:"Mary Coleman",amount:6361.51,idea_id:83},
{author:"Adam Romero",amount:6262.37,idea_id:68},
{author:"Howard Young",amount:5124.82,idea_id:1},
{author:"Nicole Walker",amount:4236.93,idea_id:63},
{author:"Matthew Carter",amount:8586.64,idea_id:28},
{author:"Joe Palmer",amount:3368.25,idea_id:57},
{author:"Ryan Montgomery",amount:4059.7,idea_id:30},
{author:"Jimmy White",amount:6253.51,idea_id:95},
{author:"Nicole Martin",amount:706.09,idea_id:61},
{author:"Peter Brooks",amount:2798.38,idea_id:97},
{author:"Alan Moore",amount:440.58,idea_id:58},
{author:"James Bowman",amount:9696.21,idea_id:36},
{author:"Karen Richards",amount:1215.68,idea_id:25},
{author:"Paul Bell",amount:5253.88,idea_id:86},
{author:"Annie Frazier",amount:3912.01,idea_id:88},
{author:"Ernest Myers",amount:848.41,idea_id:45},
{author:"Paul Hunt",amount:6733.62,idea_id:32},
{author:"Sandra Armstrong",amount:6910.06,idea_id:31},
{author:"Alan Arnold",amount:7925.45,idea_id:31},
{author:"Antonio Harvey",amount:7448.69,idea_id:78},
{author:"Joshua Garrett",amount:96.37,idea_id:79},
{author:"Tina Turner",amount:3975.12,idea_id:49},
{author:"Diane Hayes",amount:4303.17,idea_id:1},
{author:"Sean Cook",amount:8805.79,idea_id:87},
{author:"Arthur Berry",amount:7743.13,idea_id:3},
{author:"Lisa Lawrence",amount:432.41,idea_id:34},
{author:"Matthew Hall",amount:400.27,idea_id:27},
{author:"Marie Hunt",amount:6834.87,idea_id:2},
{author:"Elizabeth Wilson",amount:4781.32,idea_id:78},
{author:"Steve Stewart",amount:61.05,idea_id:39},
{author:"Timothy Robertson",amount:5337.14,idea_id:35},
{author:"Janice Morrison",amount:5198.0,idea_id:29},
{author:"Charles Chapman",amount:1009.99,idea_id:5},
{author:"Kimberly Mills",amount:8374.33,idea_id:46},
{author:"Brian Burton",amount:3262.8,idea_id:55},
{author:"Ralph Morris",amount:7607.82,idea_id:32},
{author:"Amy Vasquez",amount:9828.95,idea_id:82},
{author:"Donald Matthews",amount:4504.2,idea_id:61},
{author:"Jerry Warren",amount:125.86,idea_id:94},
{author:"Evelyn Oliver",amount:2100.55,idea_id:88},
{author:"Mary Howard",amount:6966.08,idea_id:7},
{author:"Johnny Burke",amount:9877.02,idea_id:65},
{author:"Carlos Peterson",amount:9290.75,idea_id:5},
{author:"Tammy Lewis",amount:8763.79,idea_id:18},
{author:"Jerry Weaver",amount:7877.46,idea_id:81},
{author:"George Watkins",amount:253.6,idea_id:12},
{author:"Gloria Harrison",amount:6166.23,idea_id:39},
{author:"Jane Jenkins",amount:3253.96,idea_id:82},
{author:"John Dunn",amount:8050.74,idea_id:15},
{author:"Bruce Bryant",amount:3068.68,idea_id:5},
{author:"William Carter",amount:5086.81,idea_id:31},
{author:"Amy Montgomery",amount:4806.31,idea_id:30},
{author:"Kenneth Ray",amount:9967.24,idea_id:20},
{author:"Evelyn Jordan",amount:8243.97,idea_id:65},
{author:"Ruby Roberts",amount:8703.89,idea_id:50},
{author:"Susan Montgomery",amount:5173.37,idea_id:56},
{author:"Betty Boyd",amount:5496.59,idea_id:80},
{author:"Tina Williams",amount:8871.49,idea_id:35},
{author:"Steve Kelley",amount:6016.57,idea_id:28},
{author:"Deborah Hamilton",amount:7865.72,idea_id:67},
{author:"Ernest Richardson",amount:2012.01,idea_id:67},
{author:"Kimberly Pierce",amount:5366.44,idea_id:55},
{author:"Mary Dunn",amount:991.19,idea_id:100},
{author:"Brenda West",amount:6704.08,idea_id:40},
{author:"Philip Snyder",amount:7076.69,idea_id:92},
{author:"Annie Austin",amount:5914.06,idea_id:27},
{author:"Brenda Duncan",amount:6268.45,idea_id:66},
{author:"Benjamin Gonzales",amount:2995.07,idea_id:71},
{author:"Alan Reed",amount:3122.02,idea_id:89},
{author:"Fred George",amount:7458.22,idea_id:12},
{author:"Nicholas Cunningham",amount:5262.65,idea_id:32},
{author:"Kimberly Reyes",amount:5828.61,idea_id:36},
{author:"Bobby Burke",amount:3775.8,idea_id:28},
{author:"Harold Gordon",amount:3886.19,idea_id:63},
{author:"Jeremy Green",amount:4843.33,idea_id:87},
{author:"Carl Ross",amount:2416.52,idea_id:40},
{author:"Keith Castillo",amount:9505.38,idea_id:57},
{author:"Maria Garza",amount:4010.75,idea_id:40},
{author:"Terry Murray",amount:6042.83,idea_id:63},
{author:"Catherine Reynolds",amount:1556.98,idea_id:21},
{author:"Joshua Kelly",amount:6643.31,idea_id:44},
{author:"Ralph Ford",amount:8616.19,idea_id:72},
{author:"Walter Sanders",amount:8076.44,idea_id:88},
{author:"Louis Nelson",amount:1506.24,idea_id:42},
{author:"Teresa Baker",amount:6689.4,idea_id:79},
{author:"Lois Hicks",amount:8392.91,idea_id:87},
{author:"Scott Wood",amount:1557.5,idea_id:28},
{author:"Phillip Ryan",amount:1019.79,idea_id:37},
{author:"Michael Diaz",amount:7243.59,idea_id:57},
{author:"Theresa Henry",amount:4397.02,idea_id:23},
{author:"Debra Bailey",amount:1160.6,idea_id:85},
{author:"Michael Bailey",amount:3029.26,idea_id:91},
{author:"Joyce Stone",amount:2148.4,idea_id:100},
{author:"Anna Reynolds",amount:1828.5,idea_id:17},
{author:"Chris Stewart",amount:5025.24,idea_id:96},
{author:"Heather Perkins",amount:3681.94,idea_id:8},
{author:"Kathleen Carr",amount:3975.45,idea_id:12},
{author:"Jeffrey Castillo",amount:8770.82,idea_id:80},
{author:"Jean Cruz",amount:6893.76,idea_id:44},
{author:"David Garza",amount:8673.53,idea_id:41},
{author:"Wanda Hunt",amount:5656.0,idea_id:47},
{author:"Sara Warren",amount:3615.38,idea_id:8},
{author:"Anthony Porter",amount:3262.75,idea_id:23},
{author:"Amanda Miller",amount:2536.71,idea_id:74},
{author:"Eugene Moreno",amount:9987.41,idea_id:4},
{author:"Jose Reyes",amount:3630.23,idea_id:73},
{author:"Diane Peters",amount:3848.36,idea_id:88},
{author:"Kevin Jones",amount:2252.09,idea_id:42},
{author:"Kathryn Jacobs",amount:9496.64,idea_id:12},
{author:"Thomas Black",amount:2105.06,idea_id:51},
{author:"Kathy Woods",amount:2015.24,idea_id:19},
{author:"Peter Daniels",amount:5834.03,idea_id:20},
{author:"Gloria Perry",amount:7307.43,idea_id:76},
{author:"Nicole Larson",amount:815.22,idea_id:7},
{author:"Gloria Harrison",amount:6796.67,idea_id:2},
{author:"Thomas Frazier",amount:9587.41,idea_id:51},
{author:"Marilyn Gonzales",amount:8597.88,idea_id:41},
{author:"Martin Price",amount:4746.38,idea_id:27},
{author:"Christine Brooks",amount:4095.19,idea_id:21},
{author:"Kathleen Warren",amount:5368.59,idea_id:79},
{author:"Heather Wheeler",amount:4407.67,idea_id:59},
{author:"Frances Owens",amount:852.05,idea_id:89},
{author:"Craig Armstrong",amount:9756.19,idea_id:71},
{author:"Carol Frazier",amount:4235.12,idea_id:52},
{author:"Katherine Bryant",amount:5999.62,idea_id:100},
{author:"Laura Walker",amount:3817.27,idea_id:52},
{author:"Marilyn Walker",amount:1212.0,idea_id:13},
{author:"Angela Mendoza",amount:8761.08,idea_id:60},
{author:"Anthony Wilson",amount:2866.05,idea_id:38},
{author:"Paula Lawrence",amount:135.98,idea_id:56},
{author:"Sarah Weaver",amount:5161.35,idea_id:97},
{author:"Margaret Larson",amount:9920.4,idea_id:57},
{author:"Brian Medina",amount:7167.27,idea_id:42},
{author:"Roy Webb",amount:4584.92,idea_id:95},
{author:"Anne Kelley",amount:8750.11,idea_id:47},
{author:"Eugene Kennedy",amount:5024.36,idea_id:79},
{author:"Jessica Harrison",amount:8497.36,idea_id:55},
{author:"Kenneth Meyer",amount:2165.37,idea_id:62},
{author:"Philip Garrett",amount:7460.77,idea_id:35},
{author:"Barbara Bowman",amount:7948.13,idea_id:95},
{author:"Jeremy Romero",amount:7984.22,idea_id:38},
{author:"Eugene Scott",amount:6470.69,idea_id:72},
{author:"Roy Hunt",amount:5805.26,idea_id:41},
{author:"Evelyn Murphy",amount:359.99,idea_id:11},
{author:"Linda Mendoza",amount:2177.84,idea_id:28},
{author:"Jane Perkins",amount:5071.2,idea_id:22},
{author:"Barbara Powell",amount:8774.17,idea_id:36},
{author:"Wayne Price",amount:9037.78,idea_id:66},
{author:"Roy Taylor",amount:3846.62,idea_id:62},
{author:"Peter Burns",amount:8988.47,idea_id:68},
{author:"Barbara Nelson",amount:2341.55,idea_id:42},
{author:"Stephen Berry",amount:1381.19,idea_id:5},
{author:"Harry Fowler",amount:9069.16,idea_id:48},
{author:"Amy West",amount:9356.75,idea_id:90},
{author:"Jeremy Hart",amount:1975.68,idea_id:75},
{author:"Daniel Howard",amount:1088.72,idea_id:78},
{author:"Ralph Robertson",amount:2590.18,idea_id:71},
{author:"Jack Reid",amount:5780.6,idea_id:96},
{author:"Joseph Schmidt",amount:5737.89,idea_id:78},
{author:"Eric Brown",amount:6507.01,idea_id:27},
{author:"Mary Warren",amount:3788.76,idea_id:47},
{author:"Victor Carr",amount:2772.17,idea_id:63},
{author:"Jonathan Phillips",amount:3438.91,idea_id:37},
{author:"Jennifer Flores",amount:3678.34,idea_id:89},
{author:"Mildred Carpenter",amount:2927.23,idea_id:91},
{author:"Christopher Lawson",amount:2678.66,idea_id:74},
{author:"Arthur Henry",amount:4674.54,idea_id:96},
{author:"Lori Walker",amount:4913.77,idea_id:70},
{author:"Brandon Bradley",amount:8534.17,idea_id:40},
{author:"Irene Price",amount:1924.62,idea_id:19},
{author:"Samuel Roberts",amount:7609.28,idea_id:98},
{author:"Kathleen Hughes",amount:2405.08,idea_id:36},
{author:"Kathy Cox",amount:9548.14,idea_id:13},
{author:"Sharon Peters",amount:324.57,idea_id:29},
{author:"Lillian Nichols",amount:1704.7,idea_id:76},
{author:"Sean Burton",amount:3547.01,idea_id:11},
{author:"Lawrence Fuller",amount:4747.37,idea_id:9},
{author:"Kevin Elliott",amount:7474.77,idea_id:77},
{author:"Sara Wilson",amount:5015.27,idea_id:63},
{author:"Doris Parker",amount:7918.18,idea_id:55},
{author:"Todd Phillips",amount:5389.41,idea_id:21},
{author:"Theresa White",amount:6159.48,idea_id:65},
{author:"Wayne Harris",amount:6259.49,idea_id:81},
{author:"Elizabeth Hernandez",amount:2125.89,idea_id:54},
{author:"Christine Schmidt",amount:6033.66,idea_id:11},
{author:"Rachel Wilson",amount:2245.81,idea_id:45},
{author:"Chris Rose",amount:9509.77,idea_id:26},
{author:"Kevin King",amount:1700.33,idea_id:73},
{author:"Carlos Kelly",amount:4099.22,idea_id:49},
{author:"Heather Nelson",amount:4864.94,idea_id:9},
{author:"Christine Hudson",amount:724.98,idea_id:89},
{author:"Pamela Stevens",amount:3449.74,idea_id:47},
{author:"Sean Wells",amount:9192.02,idea_id:74},
{author:"Kathy Gomez",amount:9841.05,idea_id:42},
{author:"Roger Ryan",amount:8307.91,idea_id:13},
{author:"Denise Burke",amount:7836.76,idea_id:53},
{author:"Helen Gibson",amount:5385.8,idea_id:61},
{author:"Judith Cook",amount:1046.78,idea_id:50},
{author:"Diana Perkins",amount:1321.04,idea_id:31},
{author:"Kathleen Hansen",amount:7435.51,idea_id:66},
{author:"James Flores",amount:7316.3,idea_id:53},
{author:"Jimmy Edwards",amount:2017.09,idea_id:15},
{author:"Timothy Cook",amount:5454.79,idea_id:91},
{author:"Ann Williams",amount:734.63,idea_id:42},
{author:"Timothy Wheeler",amount:4198.57,idea_id:72},
{author:"Katherine Ellis",amount:537.76,idea_id:72},
{author:"Terry Marshall",amount:3403.9,idea_id:25},
{author:"Robert Hicks",amount:3084.51,idea_id:18},
{author:"Nicholas Jordan",amount:6621.18,idea_id:70},
{author:"Roger Miller",amount:7742.72,idea_id:89},
{author:"Aaron Jacobs",amount:3599.88,idea_id:98},
{author:"Jonathan Graham",amount:3528.96,idea_id:61},
{author:"Judy Simmons",amount:6020.57,idea_id:30},
{author:"Thomas Wells",amount:4227.04,idea_id:22},
{author:"Jeremy Oliver",amount:4217.8,idea_id:96},
{author:"Norma Hunt",amount:9309.89,idea_id:76},
{author:"Cynthia Andrews",amount:9679.71,idea_id:49},
{author:"Laura Perkins",amount:6425.53,idea_id:39},
{author:"Frank Porter",amount:570.81,idea_id:31},
{author:"Steven Gardner",amount:4669.67,idea_id:28},
{author:"Catherine Stephens",amount:793.72,idea_id:49},
{author:"Carl Sanders",amount:4424.73,idea_id:51},
{author:"Ryan Riley",amount:3953.66,idea_id:57},
{author:"Deborah Morrison",amount:8279.49,idea_id:71},
{author:"Sara Meyer",amount:737.64,idea_id:53},
{author:"Lisa Ortiz",amount:793.98,idea_id:76},
{author:"Steven Gardner",amount:3951.15,idea_id:82},
{author:"Gregory Peters",amount:2372.1,idea_id:12},
{author:"Marie Marshall",amount:5973.78,idea_id:59},
{author:"Karen Woods",amount:6876.8,idea_id:76},
{author:"Ruby Freeman",amount:1451.58,idea_id:19},
{author:"Martha Wright",amount:181.75,idea_id:32},
{author:"Maria Hudson",amount:6260.94,idea_id:97},
{author:"Harold Stone",amount:8221.32,idea_id:83},
{author:"Anne Woods",amount:2402.39,idea_id:14},
{author:"Kenneth Moore",amount:8477.14,idea_id:20},
{author:"Katherine Little",amount:2014.11,idea_id:68},
{author:"Samuel Olson",amount:7544.67,idea_id:86},
{author:"Elizabeth Day",amount:8720.8,idea_id:40},
{author:"Shirley Jenkins",amount:7691.66,idea_id:17},
{author:"Jessica Romero",amount:3351.59,idea_id:68},
{author:"Donald Wheeler",amount:1006.2,idea_id:51},
{author:"Thomas Bryant",amount:6552.72,idea_id:26},
{author:"Harry Elliott",amount:8448.89,idea_id:81},
{author:"Amy Oliver",amount:2265.74,idea_id:58},
{author:"Billy Coleman",amount:6202.77,idea_id:8},
{author:"Helen Barnes",amount:9453.1,idea_id:22},
{author:"Gary Alvarez",amount:637.0,idea_id:28},
{author:"Gloria Garza",amount:674.71,idea_id:1},
{author:"Harry Williams",amount:9193.26,idea_id:22},
{author:"Sean Griffin",amount:7806.83,idea_id:61},
{author:"Janet Nichols",amount:3201.3,idea_id:25},
{author:"Tina Sullivan",amount:5561.15,idea_id:23},
{author:"Lillian Carroll",amount:8967.98,idea_id:41},
{author:"Alan Hunter",amount:2907.59,idea_id:14},
{author:"Ryan Walker",amount:2120.24,idea_id:96},
{author:"Emily Warren",amount:7550.31,idea_id:37},
{author:"Angela Reed",amount:41.7,idea_id:60},
{author:"Kelly Stevens",amount:5788.69,idea_id:82},
{author:"Donna Graham",amount:81.36,idea_id:32},
{author:"Nancy Lewis",amount:8751.59,idea_id:84},
{author:"Jeffrey Cunningham",amount:1746.39,idea_id:7},
{author:"Janet Nelson",amount:6687.32,idea_id:95},
{author:"Willie Ward",amount:6258.01,idea_id:32},
{author:"Rose Riley",amount:8082.5,idea_id:88},
{author:"Patrick Long",amount:5144.36,idea_id:15},
{author:"Patricia Garcia",amount:9985.58,idea_id:69},
{author:"James Sanders",amount:9872.58,idea_id:16},
{author:"Karen Medina",amount:437.98,idea_id:62},
{author:"Cynthia Long",amount:2559.26,idea_id:24},
{author:"Lisa Tucker",amount:3479.33,idea_id:73},
{author:"Denise Cox",amount:2650.29,idea_id:43},
{author:"Susan Ellis",amount:8044.54,idea_id:2},
{author:"Jesse Price",amount:4734.41,idea_id:8},
{author:"Jason Ross",amount:6017.16,idea_id:94},
{author:"Paula Torres",amount:5695.22,idea_id:87},
{author:"Heather Taylor",amount:7932.6,idea_id:90},
{author:"Theresa Austin",amount:1571.06,idea_id:10},
{author:"George Woods",amount:6178.93,idea_id:93},
{author:"Joan Stanley",amount:9856.57,idea_id:60},
{author:"Randy Mitchell",amount:517.87,idea_id:100},
{author:"Sandra Bishop",amount:5865.85,idea_id:23},
{author:"Laura Jordan",amount:5873.55,idea_id:82},
{author:"Kathryn Moore",amount:8436.18,idea_id:97},
{author:"Thomas Franklin",amount:6560.21,idea_id:11},
{author:"Lawrence Simmons",amount:8759.67,idea_id:39},
{author:"Carol Powell",amount:5815.21,idea_id:61},
{author:"Jessica Medina",amount:6113.5,idea_id:98},
{author:"Brenda Patterson",amount:5471.06,idea_id:59},
{author:"Amanda George",amount:2410.68,idea_id:14},
{author:"Lois Henry",amount:1942.24,idea_id:90},
{author:"Jimmy Hayes",amount:579.87,idea_id:99},
{author:"Anthony Gilbert",amount:7434.97,idea_id:4},
{author:"Frances George",amount:4714.67,idea_id:89},
{author:"Roy Gordon",amount:4295.64,idea_id:37},
{author:"Brenda Collins",amount:8808.47,idea_id:13},
{author:"Cheryl Dunn",amount:3745.92,idea_id:11},
{author:"Judith Washington",amount:2681.81,idea_id:41},
{author:"Stephanie Spencer",amount:2470.29,idea_id:45},
{author:"Ruby Allen",amount:4405.9,idea_id:5},
{author:"Terry Burton",amount:1054.23,idea_id:83},
{author:"Lori Thompson",amount:6251.13,idea_id:19},
{author:"Craig Knight",amount:2322.99,idea_id:53},
{author:"Virginia Walker",amount:868.9,idea_id:6},
{author:"Marie Sanchez",amount:2385.04,idea_id:40},
{author:"Earl Bell",amount:4298.37,idea_id:9},
{author:"Henry Hudson",amount:1178.31,idea_id:65},
{author:"Ryan Patterson",amount:6607.2,idea_id:84},
{author:"Dennis Simpson",amount:1873.79,idea_id:8},
{author:"Eric Chapman",amount:2888.73,idea_id:85},
{author:"Keith Henry",amount:5737.81,idea_id:84},
{author:"Jean Day",amount:3481.16,idea_id:15},
{author:"Karen Reyes",amount:1359.04,idea_id:62},
{author:"Jose Gardner",amount:8105.42,idea_id:21},
{author:"Bruce Robinson",amount:3739.81,idea_id:24},
{author:"Jeremy Lane",amount:2091.99,idea_id:83},
{author:"Paula Rice",amount:8996.81,idea_id:43},
{author:"Susan Peters",amount:5960.55,idea_id:74},
{author:"Julia Lawson",amount:8713.09,idea_id:61},
{author:"Stephen Ray",amount:2220.39,idea_id:40},
{author:"Steve Collins",amount:4462.04,idea_id:74},
{author:"Roy Nelson",amount:3971.0,idea_id:59},
{author:"Diana Chavez",amount:4422.65,idea_id:87},
{author:"Brian Peters",amount:6471.74,idea_id:80},
{author:"Laura Kim",amount:5939.78,idea_id:57},
{author:"Lisa Hamilton",amount:8562.02,idea_id:64},
{author:"Christopher Freeman",amount:5366.39,idea_id:31},
{author:"Rachel Hunt",amount:3137.95,idea_id:55},
{author:"Irene Mason",amount:6309.58,idea_id:77},
{author:"Evelyn Weaver",amount:6808.61,idea_id:50},
{author:"Willie Greene",amount:3258.28,idea_id:68},
{author:"Randy Wright",amount:4759.78,idea_id:17},
{author:"Matthew Jordan",amount:8032.27,idea_id:20},
{author:"Philip Black",amount:2919.55,idea_id:52},
{author:"Joyce Alexander",amount:7715.22,idea_id:90},
{author:"Christopher Torres",amount:8181.02,idea_id:86},
{author:"Ralph Price",amount:1850.23,idea_id:66},
{author:"Billy Fisher",amount:739.8,idea_id:66},
{author:"Harold Larson",amount:7710.54,idea_id:20},
{author:"Kimberly Robertson",amount:7509.56,idea_id:6},
{author:"Susan Weaver",amount:6114.67,idea_id:92},
{author:"Walter Gomez",amount:2181.04,idea_id:60},
{author:"Steven Greene",amount:1247.17,idea_id:89},
{author:"Jonathan Chavez",amount:3786.06,idea_id:91},
{author:"Kathy Ray",amount:8888.89,idea_id:94},
{author:"Carolyn Wood",amount:9089.97,idea_id:76},
{author:"Earl Graham",amount:5779.36,idea_id:2},
{author:"Diana Dixon",amount:350.76,idea_id:7},
{author:"Theresa Day",amount:9452.17,idea_id:3},
{author:"Joan Cooper",amount:5495.59,idea_id:47},
{author:"Timothy Snyder",amount:2732.31,idea_id:84},
{author:"Ronald Frazier",amount:6523.34,idea_id:67},
{author:"Samuel Harper",amount:2535.89,idea_id:88},
{author:"Judy Henderson",amount:1029.89,idea_id:98},
{author:"Nicholas Henderson",amount:1751.76,idea_id:98},
{author:"Adam Robinson",amount:5357.56,idea_id:65},
{author:"Clarence Lawrence",amount:8192.13,idea_id:73},
{author:"Doris Burns",amount:8041.91,idea_id:20},
{author:"Bobby Russell",amount:3498.94,idea_id:28},
{author:"Randy Stewart",amount:1545.07,idea_id:15},
{author:"Eugene Andrews",amount:9476.25,idea_id:49},
{author:"Terry George",amount:286.94,idea_id:13},
{author:"John Gonzales",amount:7529.82,idea_id:12},
{author:"Lori Brown",amount:1149.72,idea_id:96},
{author:"David Bell",amount:9070.1,idea_id:8},
{author:"Diana Sullivan",amount:5452.01,idea_id:63},
{author:"Michael Fields",amount:8901.13,idea_id:79},
{author:"Charles Holmes",amount:8875.03,idea_id:79},
{author:"Marilyn Cooper",amount:8792.34,idea_id:87},
{author:"Martha Murphy",amount:3138.22,idea_id:99},
{author:"Charles Roberts",amount:2207.13,idea_id:54},
{author:"Charles Morrison",amount:2588.07,idea_id:83},
{author:"Thomas Reid",amount:4701.0,idea_id:69},
{author:"Kathleen Dean",amount:9701.0,idea_id:34},
{author:"Tina Bailey",amount:5034.75,idea_id:97},
{author:"Lois Simpson",amount:5433.31,idea_id:11},
{author:"Nicole Berry",amount:7567.02,idea_id:60},
{author:"Gary Thompson",amount:721.2,idea_id:10},
{author:"Matthew Moreno",amount:2062.8,idea_id:80},
{author:"Jimmy Collins",amount:8684.88,idea_id:16},
{author:"Mary Robertson",amount:9848.78,idea_id:9},
{author:"David Andrews",amount:5945.67,idea_id:99},
{author:"Shawn Young",amount:2833.62,idea_id:24},
{author:"Ronald Rice",amount:5548.3,idea_id:1},
{author:"Maria Palmer",amount:1862.41,idea_id:55},
{author:"Carolyn Griffin",amount:2233.21,idea_id:6},
{author:"Jean Owens",amount:3660.67,idea_id:89},
{author:"Carl Tucker",amount:651.5,idea_id:58},
{author:"Kathryn Ryan",amount:3529.85,idea_id:69},
{author:"Stephen Young",amount:4916.42,idea_id:92},
{author:"Eugene Taylor",amount:4533.9,idea_id:20},
{author:"Michelle Riley",amount:3659.62,idea_id:34},
{author:"Dorothy Carter",amount:6429.64,idea_id:14},
{author:"Jack Larson",amount:8898.52,idea_id:43},
{author:"Walter Brooks",amount:8032.58,idea_id:19},
{author:"Patrick Graham",amount:3144.66,idea_id:8},
{author:"Patrick Peterson",amount:9185.27,idea_id:11},
{author:"Kevin Jenkins",amount:4880.28,idea_id:38},
{author:"Joshua Thompson",amount:7158.7,idea_id:34},
{author:"Maria Jones",amount:3837.41,idea_id:67},
{author:"Rose Hall",amount:3915.49,idea_id:70},
{author:"Ryan Bailey",amount:3389.32,idea_id:16},
{author:"Frances Bryant",amount:5901.26,idea_id:34},
{author:"Antonio Torres",amount:8088.07,idea_id:25},
{author:"Catherine Kennedy",amount:8483.23,idea_id:31},
{author:"Sean Hamilton",amount:1437.38,idea_id:21},
{author:"Phyllis Jacobs",amount:1774.84,idea_id:38},
{author:"Jonathan Dixon",amount:3532.67,idea_id:71},
{author:"Kathleen Perez",amount:2035.3,idea_id:27},
{author:"Diana Stone",amount:6207.35,idea_id:54},
{author:"Craig Perry",amount:4002.15,idea_id:21},
{author:"Norma Palmer",amount:7949.54,idea_id:48},
{author:"Sharon Carroll",amount:2169.56,idea_id:37},
{author:"George Jones",amount:8093.73,idea_id:9},
{author:"Judith Stevens",amount:3593.74,idea_id:44},
{author:"Louise Perkins",amount:7564.8,idea_id:29},
{author:"Janet Dunn",amount:6265.63,idea_id:96},
{author:"Anne Jordan",amount:9333.11,idea_id:81},
{author:"Jonathan Snyder",amount:1608.77,idea_id:60},
{author:"Ann Watson",amount:5271.11,idea_id:2},
{author:"Lawrence Cook",amount:6335.4,idea_id:15},
{author:"Justin Ryan",amount:3422.03,idea_id:33},
{author:"Rose Franklin",amount:5685.61,idea_id:47},
{author:"Christopher Cruz",amount:834.69,idea_id:90},
{author:"Juan Murray",amount:7493.53,idea_id:60},
{author:"Heather Hicks",amount:9840.67,idea_id:66},
{author:"Peter Perez",amount:4766.83,idea_id:74},
{author:"Kelly Bell",amount:5242.22,idea_id:95},
{author:"Doris Mitchell",amount:1796.02,idea_id:67},
{author:"Barbara Woods",amount:1641.87,idea_id:71},
{author:"Earl Tucker",amount:83.47,idea_id:92},
{author:"Jessica Ferguson",amount:5690.49,idea_id:69},
{author:"Jason Turner",amount:1587.2,idea_id:93},
{author:"Rachel Daniels",amount:1413.5,idea_id:25},
{author:"Teresa Gilbert",amount:4439.09,idea_id:43},
{author:"Evelyn Medina",amount:8529.99,idea_id:12},
{author:"Jennifer George",amount:3036.47,idea_id:95},
{author:"Juan Cruz",amount:3033.48,idea_id:76},
{author:"Phillip Phillips",amount:8879.2,idea_id:49},
{author:"Cynthia Stanley",amount:9094.5,idea_id:57},
{author:"Jose Carroll",amount:8483.05,idea_id:1},
{author:"Randy Ortiz",amount:8463.41,idea_id:36},
{author:"Martin Knight",amount:1291.01,idea_id:99},
{author:"Scott Gonzales",amount:7241.95,idea_id:45},
{author:"Carolyn Lynch",amount:5711.23,idea_id:41},
{author:"Catherine Vasquez",amount:7835.71,idea_id:57},
{author:"Susan Coleman",amount:4423.89,idea_id:17},
{author:"Aaron Washington",amount:8114.53,idea_id:62},
{author:"Beverly Flores",amount:8930.47,idea_id:64},
{author:"Patrick Berry",amount:7030.55,idea_id:6},
{author:"Steven Hall",amount:9955.4,idea_id:63},
{author:"Rebecca Gray",amount:8460.77,idea_id:11},
{author:"Catherine Rice",amount:4873.02,idea_id:8},
{author:"Ann Castillo",amount:8828.26,idea_id:68},
{author:"John Little",amount:6818.96,idea_id:31},
{author:"Billy Garcia",amount:622.31,idea_id:23},
{author:"Robert Martin",amount:6973.87,idea_id:32},
{author:"Donald Alexander",amount:4979.09,idea_id:18},
{author:"Tina Perkins",amount:3719.24,idea_id:36},
{author:"Ernest Watkins",amount:2582.61,idea_id:17},
{author:"Lori Hart",amount:9591.3,idea_id:25},
{author:"Deborah Johnson",amount:8827.12,idea_id:14},
{author:"Alice Ray",amount:9655.83,idea_id:65},
{author:"Brenda Morris",amount:7180.41,idea_id:63},
{author:"Denise Thompson",amount:3420.31,idea_id:30},
{author:"Jesse Morgan",amount:6361.18,idea_id:15},
{author:"Helen Rose",amount:7562.3,idea_id:83},
{author:"Henry Reed",amount:8185.23,idea_id:17},
{author:"Ashley Cooper",amount:7921.01,idea_id:56},
{author:"Samuel Johnson",amount:6858.62,idea_id:57},
{author:"Andrea Harvey",amount:504.75,idea_id:20},
{author:"Linda White",amount:7586.21,idea_id:76},
{author:"Nancy Miller",amount:5465.45,idea_id:45},
{author:"Frances Palmer",amount:2855.45,idea_id:13},
{author:"Cynthia Clark",amount:703.94,idea_id:7},
{author:"Sarah Morales",amount:3991.49,idea_id:80},
{author:"Brandon Mcdonald",amount:7469.08,idea_id:81},
{author:"Diane Gibson",amount:9351.72,idea_id:13},
{author:"Jimmy Morrison",amount:445.82,idea_id:25},
{author:"Sean Miller",amount:3314.54,idea_id:90},
{author:"Beverly Ford",amount:7547.67,idea_id:38},
{author:"Johnny Williams",amount:9099.97,idea_id:76},
{author:"Robin Jackson",amount:8844.86,idea_id:61},
{author:"Jose Cox",amount:1677.35,idea_id:85},
{author:"Lois Weaver",amount:1286.64,idea_id:46},
{author:"Patrick Carr",amount:4970.78,idea_id:45},
{author:"Jeffrey Walker",amount:3819.14,idea_id:69},
{author:"Carl Reynolds",amount:541.56,idea_id:38},
{author:"Nicholas Mitchell",amount:5312.72,idea_id:30},
{author:"Helen Smith",amount:883.91,idea_id:10},
{author:"Susan Torres",amount:8030.35,idea_id:43},
{author:"Adam Pierce",amount:8683.57,idea_id:77},
{author:"Marilyn Knight",amount:3978.04,idea_id:59},
{author:"Martha Cunningham",amount:597.71,idea_id:96},
{author:"Robert Larson",amount:6342.34,idea_id:2},
{author:"Thomas Tucker",amount:6320.02,idea_id:42},
{author:"Ernest Lawson",amount:4582.49,idea_id:45},
{author:"Jeffrey Gordon",amount:1864.67,idea_id:49},
{author:"Justin Fernandez",amount:5139.97,idea_id:1},
{author:"Eugene Mason",amount:394.03,idea_id:16},
{author:"Wayne Murphy",amount:8869.01,idea_id:69},
{author:"Antonio Sanders",amount:1070.88,idea_id:53},
{author:"Judith Collins",amount:2687.4,idea_id:73},
{author:"Margaret Harvey",amount:827.83,idea_id:66},
{author:"Anthony Williamson",amount:9438.29,idea_id:23},
{author:"Ashley Bell",amount:4393.22,idea_id:43},
{author:"Craig Lawrence",amount:3402.29,idea_id:99},
{author:"Irene Gomez",amount:9715.93,idea_id:89},
{author:"Tina Gutierrez",amount:3781.78,idea_id:46},
{author:"Joshua Montgomery",amount:3418.4,idea_id:32},
{author:"Lisa Harris",amount:4591.15,idea_id:37},
{author:"Stephanie Woods",amount:9631.43,idea_id:43},
{author:"Kathy Cunningham",amount:3204.44,idea_id:95},
{author:"Michelle Morris",amount:3618.96,idea_id:69},
{author:"Russell Sullivan",amount:7819.85,idea_id:32},
{author:"Paul Garcia",amount:8740.0,idea_id:97},
{author:"Ernest Washington",amount:9343.47,idea_id:61},
{author:"Katherine Nelson",amount:1481.04,idea_id:43},
{author:"Timothy Johnson",amount:5059.19,idea_id:53},
{author:"Kathy Clark",amount:5053.99,idea_id:73},
{author:"Jesse Frazier",amount:9315.58,idea_id:22},
{author:"Randy Robertson",amount:7502.57,idea_id:51},
{author:"Jeffrey Powell",amount:9915.91,idea_id:70},
{author:"Lois Riley",amount:3169.73,idea_id:66},
{author:"Alice Fields",amount:6133.69,idea_id:82},
{author:"Judith Alexander",amount:1913.61,idea_id:31},
{author:"Scott Schmidt",amount:2476.68,idea_id:83},
{author:"Deborah Hart",amount:6206.02,idea_id:62},
{author:"Helen Kim",amount:2986.71,idea_id:20},
{author:"Julie Richards",amount:2658.69,idea_id:71},
{author:"Philip Ortiz",amount:9245.3,idea_id:67},
{author:"Jerry Knight",amount:4347.71,idea_id:67},
{author:"Raymond Bradley",amount:339.56,idea_id:83},
{author:"Bobby Gardner",amount:2690.74,idea_id:18},
{author:"Jesse Duncan",amount:1226.12,idea_id:87},
{author:"Michael Chavez",amount:4985.1,idea_id:1},
{author:"Benjamin Alvarez",amount:9527.24,idea_id:50},
{author:"Peter Hamilton",amount:5346.22,idea_id:43},
{author:"Susan Mills",amount:2129.31,idea_id:25},
{author:"Janice Meyer",amount:1095.22,idea_id:24},
{author:"Aaron Alvarez",amount:5500.2,idea_id:65},
{author:"Michelle Allen",amount:1312.1,idea_id:78},
{author:"Christina Reynolds",amount:3288.62,idea_id:77},
{author:"Judy Little",amount:1460.98,idea_id:52},
{author:"Louis Simmons",amount:9974.77,idea_id:93},
{author:"Donald Wallace",amount:5776.64,idea_id:63},
{author:"Ann Bradley",amount:3683.8,idea_id:96},
{author:"Daniel Austin",amount:4340.25,idea_id:28},
{author:"Edward Fuller",amount:4917.68,idea_id:53},
{author:"Carlos Sanders",amount:1236.24,idea_id:54},
{author:"Theresa Clark",amount:495.07,idea_id:71},
{author:"Lillian Robinson",amount:4516.27,idea_id:100},
{author:"Judy Gonzalez",amount:8983.81,idea_id:1},
{author:"Elizabeth Howell",amount:1522.47,idea_id:73},
{author:"Kevin Wilson",amount:3090.36,idea_id:94},
{author:"Phyllis Bennett",amount:4216.55,idea_id:97},
{author:"Bonnie Lawrence",amount:8145.65,idea_id:54},
{author:"Harold Lane",amount:4042.12,idea_id:8},
{author:"Wayne Taylor",amount:2532.02,idea_id:14},
{author:"Robin Lewis",amount:9398.87,idea_id:30},
{author:"Stephanie Johnston",amount:445.53,idea_id:78},
{author:"Ralph Lopez",amount:452.67,idea_id:41},
{author:"Ronald Wagner",amount:6139.85,idea_id:91},
{author:"Alice Burns",amount:1178.88,idea_id:46},
{author:"Tina Smith",amount:3820.91,idea_id:75},
{author:"John Lane",amount:8808.28,idea_id:100},
{author:"Cynthia Warren",amount:3096.15,idea_id:18},
{author:"Jeffrey Allen",amount:1116.01,idea_id:65},
{author:"Michelle Harris",amount:2316.9,idea_id:1},
{author:"Anne Cunningham",amount:8827.56,idea_id:38},
{author:"Bruce Hudson",amount:638.63,idea_id:38},
{author:"Mildred Sims",amount:9247.19,idea_id:38},
{author:"Kimberly Banks",amount:6422.87,idea_id:62},
{author:"Irene Moore",amount:3234.08,idea_id:72},
{author:"Willie Lewis",amount:9538.9,idea_id:4},
{author:"David Howell",amount:5889.15,idea_id:19},
{author:"Scott Myers",amount:3781.95,idea_id:18},
{author:"Bruce Harper",amount:5808.6,idea_id:42},
{author:"Sarah Flores",amount:2258.9,idea_id:46},
{author:"Eugene Cunningham",amount:5628.18,idea_id:14},
{author:"Joyce Stone",amount:9357.39,idea_id:39},
{author:"George Thomas",amount:2175.51,idea_id:81},
{author:"Paul Peterson",amount:5386.91,idea_id:92},
{author:"Laura Bradley",amount:634.0,idea_id:87},
{author:"Matthew Turner",amount:1895.85,idea_id:31},
{author:"Jonathan Gibson",amount:1789.1,idea_id:65},
{author:"Tina Nelson",amount:6290.18,idea_id:11},
{author:"Jimmy Johnson",amount:2845.24,idea_id:63},
{author:"Beverly Hall",amount:733.44,idea_id:66},
{author:"Frances Stanley",amount:8513.76,idea_id:2},
{author:"Shawn Jenkins",amount:4199.36,idea_id:46},
{author:"Kevin Turner",amount:724.46,idea_id:98},
{author:"Pamela Larson",amount:5059.52,idea_id:52},
{author:"Dennis Marshall",amount:745.9,idea_id:54},
{author:"Christine Sanchez",amount:3265.09,idea_id:86},
{author:"Carol Turner",amount:7746.46,idea_id:65},
{author:"Matthew Turner",amount:9562.04,idea_id:98},
{author:"Donna Thomas",amount:9525.68,idea_id:90},
{author:"Jeffrey Duncan",amount:2579.15,idea_id:92},
{author:"Stephen Watkins",amount:5483.89,idea_id:33},
{author:"Jennifer Brown",amount:7518.26,idea_id:91},
{author:"Frank Hernandez",amount:9556.55,idea_id:58},
{author:"Brenda Fox",amount:2878.94,idea_id:72},
{author:"Emily Chapman",amount:8107.97,idea_id:72},
{author:"Bobby Ray",amount:2726.9,idea_id:32},
{author:"Wanda Morgan",amount:6447.42,idea_id:7},
{author:"Cheryl Howard",amount:2700.74,idea_id:94},
{author:"Louis Scott",amount:976.3,idea_id:29},
{author:"Clarence Bennett",amount:8829.9,idea_id:30},
{author:"Ann Wright",amount:8678.04,idea_id:19},
{author:"Martha Romero",amount:4805.06,idea_id:36},
{author:"Dorothy Perry",amount:8369.31,idea_id:63},
{author:"Donna Oliver",amount:3156.83,idea_id:16},
{author:"Harry Jordan",amount:4267.18,idea_id:76},
{author:"Angela Harris",amount:4581.6,idea_id:52},
{author:"Joseph Ramos",amount:7097.35,idea_id:39},
{author:"Ronald Bowman",amount:1855.52,idea_id:9},
{author:"Joan Kelley",amount:7752.67,idea_id:36},
{author:"Roger Nguyen",amount:6641.23,idea_id:22},
{author:"Amanda Kennedy",amount:6362.68,idea_id:59},
{author:"Daniel Gonzalez",amount:5007.86,idea_id:35},
{author:"Mary Hudson",amount:7421.35,idea_id:41},
{author:"Amanda Day",amount:7075.02,idea_id:50},
{author:"Ruth Garza",amount:9402.39,idea_id:59},
{author:"Henry Long",amount:6398.53,idea_id:24},
{author:"Willie Wood",amount:7572.11,idea_id:65},
{author:"Ruby Green",amount:9775.65,idea_id:35},
{author:"Roger Anderson",amount:3823.44,idea_id:7},
{author:"Jean Taylor",amount:7521.9,idea_id:19},
{author:"Carol Allen",amount:5229.01,idea_id:8},
{author:"Theresa Perkins",amount:4355.26,idea_id:20},
{author:"Lisa Mccoy",amount:3592.08,idea_id:3},
{author:"Eugene Austin",amount:1871.58,idea_id:90},
{author:"Pamela Pierce",amount:1102.12,idea_id:28},
{author:"Samuel Jordan",amount:6597.09,idea_id:74},
{author:"Helen Oliver",amount:8699.59,idea_id:85},
{author:"Earl Bradley",amount:2760.81,idea_id:62},
{author:"Deborah Carroll",amount:2687.69,idea_id:30},
{author:"Johnny Smith",amount:7893.0,idea_id:96},
{author:"Lawrence Chavez",amount:5626.75,idea_id:63},
{author:"Terry Nguyen",amount:6672.58,idea_id:42},
{author:"Raymond Watkins",amount:5089.32,idea_id:94},
{author:"Stephanie Morrison",amount:6836.14,idea_id:72},
{author:"Carl Oliver",amount:6101.57,idea_id:43},
{author:"Dennis Chavez",amount:9683.32,idea_id:95},
{author:"Steve Kelly",amount:6310.52,idea_id:49},
{author:"Jonathan Hernandez",amount:6221.86,idea_id:77},
{author:"Paula Reid",amount:8633.99,idea_id:99},
{author:"Timothy Burke",amount:3237.29,idea_id:43},
{author:"Kevin Lane",amount:6863.16,idea_id:11},
{author:"Edward Wallace",amount:5048.25,idea_id:43},
{author:"Timothy Hicks",amount:7288.33,idea_id:40},
{author:"Craig Perry",amount:7469.9,idea_id:62},
{author:"Angela Lane",amount:5088.78,idea_id:18},
{author:"Jane Butler",amount:579.84,idea_id:79},
{author:"Rose Gardner",amount:7876.64,idea_id:27},
{author:"Chris Bennett",amount:1335.39,idea_id:39},
{author:"Julia Garrett",amount:1787.15,idea_id:58},
{author:"Susan Fernandez",amount:9142.03,idea_id:15},
{author:"Martha Reid",amount:7212.77,idea_id:58},
{author:"Anna Gilbert",amount:4216.77,idea_id:31},
{author:"Douglas Lynch",amount:8274.13,idea_id:93},
{author:"Martin Gonzalez",amount:2643.51,idea_id:15},
{author:"Stephanie Hughes",amount:9595.96,idea_id:84},
{author:"Louise Ryan",amount:3930.29,idea_id:82},
{author:"Johnny Phillips",amount:7494.46,idea_id:35},
{author:"Mildred Gray",amount:362.33,idea_id:68},
{author:"Ernest Adams",amount:5395.4,idea_id:34},
{author:"Todd Smith",amount:9789.91,idea_id:14},
{author:"Robert Gordon",amount:1770.04,idea_id:99},
{author:"Teresa Watson",amount:2087.07,idea_id:71},
{author:"Jacqueline Riley",amount:9797.99,idea_id:58},
{author:"Carol Wood",amount:9378.2,idea_id:8},
{author:"Amy Kelley",amount:8818.39,idea_id:31},
{author:"Doris Dixon",amount:6334.07,idea_id:93},
{author:"Dorothy Nichols",amount:8192.87,idea_id:71},
{author:"Amy Ryan",amount:2349.03,idea_id:55},
{author:"Larry Reyes",amount:2542.48,idea_id:90},
{author:"Anna Ford",amount:2781.86,idea_id:15},
{author:"Gregory Perkins",amount:2863.06,idea_id:95},
{author:"Randy Taylor",amount:7843.87,idea_id:80},
{author:"Marilyn Hart",amount:4936.8,idea_id:15},
{author:"Henry Flores",amount:7607.37,idea_id:22},
{author:"Judith Martin",amount:2777.23,idea_id:49},
{author:"Aaron Hamilton",amount:1177.05,idea_id:9},
{author:"Joshua Peterson",amount:3782.38,idea_id:36},
{author:"Christine Henderson",amount:848.99,idea_id:76},
{author:"Marilyn Robertson",amount:4339.86,idea_id:92},
{author:"Donna Wood",amount:6765.2,idea_id:5},
{author:"Harold Dixon",amount:7790.12,idea_id:69},
{author:"Roger Murray",amount:5863.67,idea_id:39},
{author:"Roy Fox",amount:7400.39,idea_id:55},
{author:"Kenneth Garza",amount:9889.03,idea_id:34},
{author:"Harold Owens",amount:7315.28,idea_id:30},
{author:"Wayne White",amount:3045.7,idea_id:56},
{author:"Steve Holmes",amount:5460.6,idea_id:90},
{author:"Theresa Jones",amount:4119.39,idea_id:38},
{author:"Ruby George",amount:7623.97,idea_id:46},
{author:"Chris Knight",amount:3229.29,idea_id:41},
{author:"Beverly Ray",amount:199.85,idea_id:83},
{author:"Billy Patterson",amount:2960.24,idea_id:27},
{author:"Randy Fowler",amount:8278.44,idea_id:99},
{author:"Craig Schmidt",amount:9648.23,idea_id:56},
{author:"Craig Dunn",amount:6295.41,idea_id:76},
{author:"Kimberly Lawrence",amount:353.36,idea_id:73},
{author:"James Murphy",amount:3052.28,idea_id:19},
{author:"Jack Nelson",amount:41.72,idea_id:84},
{author:"Willie Cole",amount:4414.91,idea_id:53},
{author:"Ralph Lopez",amount:5038.24,idea_id:3},
{author:"Dennis Mitchell",amount:933.48,idea_id:58},
{author:"Richard Chapman",amount:491.75,idea_id:73},
{author:"Carlos Ray",amount:68.07,idea_id:74},
{author:"Richard King",amount:7194.86,idea_id:95},
{author:"Diane Jackson",amount:6498.05,idea_id:51},
{author:"Charles Ramos",amount:521.42,idea_id:29},
{author:"Michael Matthews",amount:7561.77,idea_id:39},
{author:"Craig Meyer",amount:2795.76,idea_id:62},
{author:"Anna Howell",amount:2276.7,idea_id:40},
{author:"Jean Snyder",amount:5799.6,idea_id:19},
{author:"Norma Butler",amount:8597.12,idea_id:26},
{author:"Eugene Kennedy",amount:1637.76,idea_id:55},
{author:"Christina Ramos",amount:5891.76,idea_id:21},
{author:"Michael Williams",amount:6004.58,idea_id:71},
{author:"Anne George",amount:3536.04,idea_id:25},
{author:"Jose Mason",amount:3545.11,idea_id:8},
{author:"Marie Hernandez",amount:2770.75,idea_id:87},
{author:"Joseph Gonzales",amount:259.8,idea_id:59},
{author:"Carl Hernandez",amount:9444.82,idea_id:25},
{author:"Marie Rogers",amount:5574.96,idea_id:37},
{author:"Antonio Jacobs",amount:5356.79,idea_id:100},
{author:"Amy Perkins",amount:2163.62,idea_id:9},
{author:"Frances Andrews",amount:8303.59,idea_id:40},
{author:"Ruby Allen",amount:5096.76,idea_id:48},
{author:"Nicholas Powell",amount:3627.92,idea_id:99},
{author:"Maria Wells",amount:735.5,idea_id:48},
{author:"Anne Jacobs",amount:6926.27,idea_id:28},
{author:"Judith Ferguson",amount:125.39,idea_id:24},
{author:"Emily Montgomery",amount:8717.5,idea_id:12},
{author:"Wayne Lane",amount:4222.66,idea_id:86},
{author:"James Perry",amount:7519.54,idea_id:31},
{author:"Robin Bailey",amount:4137.84,idea_id:7},
{author:"Peter Clark",amount:8755.03,idea_id:86},
{author:"Ashley Stone",amount:4626.7,idea_id:55},
{author:"Nicholas Gonzalez",amount:8104.9,idea_id:81},
{author:"Henry Young",amount:3466.2,idea_id:74},
{author:"Howard Mills",amount:6317.38,idea_id:49},
{author:"Bruce Medina",amount:504.23,idea_id:20},
{author:"Gary Anderson",amount:9736.27,idea_id:68},
{author:"Irene Butler",amount:9750.73,idea_id:34},
{author:"Ryan Lane",amount:8121.01,idea_id:22},
{author:"Frances Young",amount:983.63,idea_id:82},
{author:"Marilyn Sanders",amount:1098.85,idea_id:63},
{author:"Bonnie Harrison",amount:1841.61,idea_id:56},
{author:"Angela Hunt",amount:5609.58,idea_id:56},
{author:"Marie Wright",amount:9698.28,idea_id:90},
{author:"Bobby Butler",amount:8515.65,idea_id:97},
{author:"Doris Nelson",amount:8566.92,idea_id:77},
{author:"Jeremy Oliver",amount:4803.62,idea_id:68},
{author:"Tina Walker",amount:1834.81,idea_id:9},
{author:"Helen Harris",amount:1752.95,idea_id:47},
{author:"Benjamin Morgan",amount:8158.66,idea_id:82},
{author:"Terry Gibson",amount:5935.18,idea_id:22},
{author:"Cheryl Dean",amount:9546.68,idea_id:26},
{author:"Timothy Mason",amount:419.39,idea_id:71},
{author:"Brian Howard",amount:6808.18,idea_id:39},
{author:"Carol Reid",amount:4782.08,idea_id:88},
{author:"Denise Jenkins",amount:555.34,idea_id:2},
{author:"Louise Warren",amount:6726.63,idea_id:12},
{author:"Scott Montgomery",amount:6007.52,idea_id:16},
{author:"Paula Mendoza",amount:5418.74,idea_id:79},
{author:"Helen Morrison",amount:5180.78,idea_id:66},
{author:"Eugene Armstrong",amount:8586.46,idea_id:53},
{author:"Amanda Duncan",amount:81.63,idea_id:78},
{author:"Stephanie Hayes",amount:3040.92,idea_id:33},
{author:"Daniel Diaz",amount:7254.93,idea_id:9},
{author:"Louise Wilson",amount:1135.27,idea_id:12},
{author:"Roger Cook",amount:5939.96,idea_id:54},
{author:"Janet Johnston",amount:1232.91,idea_id:1},
{author:"Jeremy Bell",amount:3724.95,idea_id:93},
{author:"Lori Perkins",amount:4880.57,idea_id:29},
{author:"Jonathan James",amount:1875.53,idea_id:34},
{author:"Ralph Howell",amount:4929.27,idea_id:48},
{author:"Theresa Grant",amount:6894.19,idea_id:56},
{author:"Amy Gordon",amount:8167.64,idea_id:31},
{author:"Carol Ray",amount:1241.48,idea_id:72},
{author:"Tammy Hudson",amount:7616.99,idea_id:16},
{author:"Keith Sullivan",amount:8583.25,idea_id:64},
{author:"Gerald Alexander",amount:1670.36,idea_id:26},
{author:"Paula Allen",amount:3640.7,idea_id:83},
{author:"Richard Chapman",amount:744.55,idea_id:77},
{author:"Randy Austin",amount:3488.39,idea_id:94},
{author:"Kathy Harrison",amount:4885.22,idea_id:91},
{author:"Shirley Lane",amount:119.12,idea_id:85},
{author:"Joyce Edwards",amount:4346.18,idea_id:56},
{author:"Amanda Henry",amount:1989.1,idea_id:13},
{author:"Diane Ray",amount:8415.22,idea_id:31},
{author:"Charles Ryan",amount:5588.13,idea_id:49},
{author:"Roy West",amount:5836.51,idea_id:78},
{author:"Elizabeth Lee",amount:3912.1,idea_id:70},
{author:"Christine Reynolds",amount:2544.38,idea_id:7},
{author:"Carol Austin",amount:6316.15,idea_id:68},
{author:"Marie Long",amount:6842.99,idea_id:50},
{author:"Virginia Fuller",amount:5604.4,idea_id:8},
{author:"Matthew Miller",amount:420.73,idea_id:21},
{author:"Stephen Daniels",amount:2565.17,idea_id:48},
{author:"Lillian Simpson",amount:3957.51,idea_id:31},
{author:"Jerry Woods",amount:2016.9,idea_id:40},
{author:"Jose Bishop",amount:1259.17,idea_id:86},
{author:"Mark Rose",amount:1799.97,idea_id:81},
{author:"Alan Wells",amount:830.4,idea_id:19},
{author:"Rachel Mccoy",amount:9023.62,idea_id:30},
{author:"Phyllis Flores",amount:3088.11,idea_id:42},
{author:"Beverly Campbell",amount:7532.96,idea_id:2},
{author:"Donald Bishop",amount:9022.38,idea_id:37},
{author:"Kathryn George",amount:3891.33,idea_id:47},
{author:"Deborah Sullivan",amount:2800.98,idea_id:13},
{author:"James Jordan",amount:5823.83,idea_id:10},
{author:"Howard Carter",amount:9331.48,idea_id:89},
{author:"Sandra Ross",amount:4344.78,idea_id:34},
{author:"Gregory Robinson",amount:8711.66,idea_id:100},
{author:"Jack Nguyen",amount:494.13,idea_id:53},
{author:"Anthony Bishop",amount:5653.53,idea_id:34},
{author:"Ernest Hayes",amount:8388.26,idea_id:12},
{author:"Louis Stevens",amount:6851.45,idea_id:76},
{author:"Betty Howell",amount:1334.38,idea_id:49},
{author:"Kevin Gardner",amount:2226.35,idea_id:3},
{author:"Joyce Hicks",amount:4394.41,idea_id:55},
{author:"Tammy Dean",amount:6887.31,idea_id:29},
{author:"Ernest Jordan",amount:4617.89,idea_id:2},
{author:"Shawn Cook",amount:1307.75,idea_id:59},
{author:"Shawn Hunter",amount:6106.06,idea_id:44},
{author:"Antonio Stewart",amount:488.13,idea_id:41},
{author:"Jose Gonzalez",amount:2484.24,idea_id:8},
{author:"Lois Knight",amount:4550.07,idea_id:59},
{author:"Lisa Butler",amount:3107.36,idea_id:42},
{author:"Todd Foster",amount:5482.87,idea_id:70},
{author:"Brian Nelson",amount:1042.84,idea_id:70},
{author:"Gary Jones",amount:6722.44,idea_id:60},
{author:"George Pierce",amount:4312.24,idea_id:87},
{author:"Sandra Henderson",amount:342.58,idea_id:63},
{author:"Victor Romero",amount:3532.97,idea_id:44},
{author:"Karen Collins",amount:3839.15,idea_id:58},
{author:"Rose Crawford",amount:647.3,idea_id:57},
{author:"Arthur Rodriguez",amount:70.99,idea_id:48},
{author:"Matthew Gonzalez",amount:455.27,idea_id:19},
{author:"Ralph Cole",amount:9984.39,idea_id:45},
{author:"Jean Jones",amount:8324.75,idea_id:18},
{author:"Timothy Harper",amount:1325.32,idea_id:84},
{author:"Maria Richardson",amount:9011.27,idea_id:82},
{author:"Todd Ryan",amount:2496.59,idea_id:93},
{author:"Nancy Arnold",amount:7392.73,idea_id:16},
{author:"Jason Johnson",amount:1979.83,idea_id:64},
{author:"Catherine Brooks",amount:7414.41,idea_id:48},
{author:"Martin Williamson",amount:8839.23,idea_id:34},
{author:"Martin Boyd",amount:4052.4,idea_id:72},
{author:"Gregory Ward",amount:9711.18,idea_id:90},
{author:"Joe Rogers",amount:7472.99,idea_id:2},
{author:"Sandra Hernandez",amount:2117.79,idea_id:14},
{author:"Todd Spencer",amount:3235.92,idea_id:95},
{author:"Anne Williamson",amount:1338.08,idea_id:51},
{author:"Gary Kennedy",amount:8280.29,idea_id:82},
{author:"Phyllis Graham",amount:6485.15,idea_id:54},
{author:"Julia Barnes",amount:3009.23,idea_id:70},
{author:"Fred Jenkins",amount:6191.78,idea_id:9},
{author:"Norma Hayes",amount:9858.42,idea_id:34},
{author:"Andrew Baker",amount:3323.77,idea_id:6},
{author:"Diana Reed",amount:2122.62,idea_id:16},
{author:"Victor Smith",amount:2634.26,idea_id:15},
{author:"Maria Ellis",amount:1827.81,idea_id:22},
{author:"Joyce Perry",amount:8882.61,idea_id:27},
{author:"Julie Wells",amount:7230.91,idea_id:49},
{author:"Anna Reed",amount:3467.69,idea_id:70},
{author:"Benjamin Cole",amount:6164.78,idea_id:50},
{author:"Samuel Jacobs",amount:1188.76,idea_id:43},
{author:"Victor Martinez",amount:9256.78,idea_id:71},
{author:"Martha Harper",amount:1399.81,idea_id:31},
{author:"Jack Stevens",amount:9469.96,idea_id:75},
{author:"Eugene Ortiz",amount:646.7,idea_id:34},
{author:"Rebecca Howard",amount:4999.58,idea_id:99},
{author:"Julia Cruz",amount:2950.26,idea_id:92},
{author:"Christopher Rose",amount:6887.56,idea_id:89},
{author:"Juan Gordon",amount:2866.31,idea_id:76},
{author:"Todd Crawford",amount:3214.19,idea_id:71},
{author:"Fred Rice",amount:2518.03,idea_id:3},
{author:"Doris Smith",amount:1546.95,idea_id:26},
{author:"Johnny Armstrong",amount:1216.36,idea_id:24},
{author:"Jeffrey Wright",amount:5079.74,idea_id:77},
{author:"James Lewis",amount:1761.32,idea_id:33},
{author:"Carol Oliver",amount:2112.01,idea_id:78},
{author:"Lori Martin",amount:2277.1,idea_id:36},
{author:"Brenda Hanson",amount:8533.66,idea_id:89},
{author:"Larry Armstrong",amount:9302.12,idea_id:40},
{author:"Eugene Cole",amount:2682.94,idea_id:14},
{author:"Shirley Spencer",amount:6791.88,idea_id:14},
{author:"Kimberly Gonzales",amount:6046.34,idea_id:89},
{author:"Jose Foster",amount:7475.59,idea_id:85},
{author:"Lori Hill",amount:9731.54,idea_id:60},
{author:"Margaret Snyder",amount:1518.15,idea_id:91},
{author:"Louise Butler",amount:9594.97,idea_id:74},
{author:"Eric Lopez",amount:8723.74,idea_id:35},
{author:"Terry Powell",amount:6254.52,idea_id:11},
{author:"Shawn Adams",amount:1285.89,idea_id:78},
{author:"Earl Foster",amount:7630.64,idea_id:97},
{author:"Ralph Collins",amount:7306.76,idea_id:23},
{author:"Ruth Brooks",amount:1604.47,idea_id:49},
{author:"Louis Stewart",amount:2595.09,idea_id:19},
{author:"Joan Clark",amount:9981.29,idea_id:45},
{author:"Matthew Kelley",amount:5407.17,idea_id:96},
{author:"Jessica Stewart",amount:5588.81,idea_id:86},
{author:"Ralph Miller",amount:9939.54,idea_id:56},
{author:"Albert Wagner",amount:760.27,idea_id:41},
{author:"Robert Lawrence",amount:7173.08,idea_id:15},
{author:"Antonio Davis",amount:8119.84,idea_id:62},
{author:"Annie Morales",amount:6019.23,idea_id:90},
{author:"Ralph Russell",amount:4686.89,idea_id:40},
{author:"Joan Reyes",amount:2571.97,idea_id:53},
{author:"Chris George",amount:6437.97,idea_id:19},
{author:"Billy Jones",amount:8255.49,idea_id:50},
{author:"Harry Graham",amount:5245.96,idea_id:80},
{author:"Robin Johnston",amount:5779.31,idea_id:81},
{author:"Frances Flores",amount:7617.15,idea_id:5},
{author:"David Bell",amount:6050.85,idea_id:38},
{author:"Victor Reid",amount:1242.25,idea_id:65},
{author:"Daniel Richardson",amount:9987.95,idea_id:35},
{author:"Antonio Patterson",amount:6799.28,idea_id:33},
{author:"Todd Edwards",amount:3846.78,idea_id:30}])
